export const USER_LEVELS = {
  L5_ADMIN: 'L5_ADMIN',
  L4_AGENT: 'L4_AGENT', 
  L3_SUBCLIENT: 'L3_SUBCLIENT',
  L2_CLIENT: 'L2_CLIENT'
}

export const USER_LEVEL_NAMES = {
  [USER_LEVELS.L5_ADMIN]: 'System Administrator',
  [USER_LEVELS.L4_AGENT]: 'Agent/Advisor',
  [USER_LEVELS.L3_SUBCLIENT]: 'Sub-Client',
  [USER_LEVELS.L2_CLIENT]: 'Client'
}

export const TRANSACTION_TYPES = {
  BUY: 'BUY',
  SELL: 'SELL',
  DIVIDEND: 'DIVIDEND',
  INTEREST: 'INTEREST',
  FEE: 'FEE',
  TAX: 'TAX',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  CORPORATE_ACTION: 'CORPORATE_ACTION',
  SPLIT: 'SPLIT',
  MERGER: 'MERGER',
  SPINOFF: 'SPINOFF'
}

export const TRANSACTION_TYPE_NAMES = {
  [TRANSACTION_TYPES.BUY]: 'Buy',
  [TRANSACTION_TYPES.SELL]: 'Sell',
  [TRANSACTION_TYPES.DIVIDEND]: 'Dividend',
  [TRANSACTION_TYPES.INTEREST]: 'Interest',
  [TRANSACTION_TYPES.FEE]: 'Fee',
  [TRANSACTION_TYPES.TAX]: 'Tax',
  [TRANSACTION_TYPES.TRANSFER_IN]: 'Transfer In',
  [TRANSACTION_TYPES.TRANSFER_OUT]: 'Transfer Out',
  [TRANSACTION_TYPES.CORPORATE_ACTION]: 'Corporate Action',
  [TRANSACTION_TYPES.SPLIT]: 'Stock Split',
  [TRANSACTION_TYPES.MERGER]: 'Merger',
  [TRANSACTION_TYPES.SPINOFF]: 'Spinoff'
}

export const ACCOUNT_TYPES = {
  INVESTMENT: 'INVESTMENT',
  CASH: 'CASH',
  MARGIN: 'MARGIN',
  RETIREMENT: 'RETIREMENT',
  TRUST: 'TRUST',
  CUSTODIAL: 'CUSTODIAL'
}

export const ACCOUNT_TYPE_NAMES = {
  [ACCOUNT_TYPES.INVESTMENT]: 'Investment Account',
  [ACCOUNT_TYPES.CASH]: 'Cash Account',
  [ACCOUNT_TYPES.MARGIN]: 'Margin Account',
  [ACCOUNT_TYPES.RETIREMENT]: 'Retirement Account',
  [ACCOUNT_TYPES.TRUST]: 'Trust Account',
  [ACCOUNT_TYPES.CUSTODIAL]: 'Custodial Account'
}

export const ASSET_CLASSES = {
  EQUITY: 'EQUITY',
  FIXED_INCOME: 'FIXED_INCOME',
  CASH: 'CASH',
  ALTERNATIVE: 'ALTERNATIVE',
  COMMODITY: 'COMMODITY',
  REAL_ESTATE: 'REAL_ESTATE',
  DERIVATIVE: 'DERIVATIVE'
}

export const ASSET_CLASS_NAMES = {
  [ASSET_CLASSES.EQUITY]: 'Equity',
  [ASSET_CLASSES.FIXED_INCOME]: 'Fixed Income',
  [ASSET_CLASSES.CASH]: 'Cash & Cash Equivalents',
  [ASSET_CLASSES.ALTERNATIVE]: 'Alternative Investments',
  [ASSET_CLASSES.COMMODITY]: 'Commodities',
  [ASSET_CLASSES.REAL_ESTATE]: 'Real Estate',
  [ASSET_CLASSES.DERIVATIVE]: 'Derivatives'
}

export const ENTRY_STATUS = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED'
}

export const ENTRY_STATUS_NAMES = {
  [ENTRY_STATUS.DRAFT]: 'Draft',
  [ENTRY_STATUS.POSTED]: 'Posted'
}

export const CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  JPY: 'JPY',
  CAD: 'CAD',
  AUD: 'AUD',
  CHF: 'CHF'
}

export const CURRENCY_NAMES = {
  [CURRENCIES.USD]: 'US Dollar',
  [CURRENCIES.EUR]: 'Euro',
  [CURRENCIES.GBP]: 'British Pound',
  [CURRENCIES.JPY]: 'Japanese Yen',
  [CURRENCIES.CAD]: 'Canadian Dollar',
  [CURRENCIES.AUD]: 'Australian Dollar',
  [CURRENCIES.CHF]: 'Swiss Franc'
}

export const CURRENCY_SYMBOLS = {
  [CURRENCIES.USD]: '$',
  [CURRENCIES.EUR]: '€',
  [CURRENCIES.GBP]: '£',
  [CURRENCIES.JPY]: '¥',
  [CURRENCIES.CAD]: 'C$',
  [CURRENCIES.AUD]: 'A$',
  [CURRENCIES.CHF]: 'CHF'
}

export const FEE_TYPES = {
  MANAGEMENT: 'MANAGEMENT',
  PERFORMANCE: 'PERFORMANCE',
  TRANSACTION: 'TRANSACTION',
  CUSTODIAL: 'CUSTODIAL',
  ADMINISTRATIVE: 'ADMINISTRATIVE'
}

export const FEE_TYPE_NAMES = {
  [FEE_TYPES.MANAGEMENT]: 'Management Fee',
  [FEE_TYPES.PERFORMANCE]: 'Performance Fee',
  [FEE_TYPES.TRANSACTION]: 'Transaction Fee',
  [FEE_TYPES.CUSTODIAL]: 'Custodial Fee',
  [FEE_TYPES.ADMINISTRATIVE]: 'Administrative Fee'
}

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  VIEW: 'VIEW',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT'
}

export const ENTITY_TYPES = {
  USER: 'USER',
  CLIENT_PROFILE: 'CLIENT_PROFILE',
  TRANSACTION: 'TRANSACTION',
  POSITION: 'POSITION',
  ACCOUNT: 'ACCOUNT',
  SECURITY: 'SECURITY',
  REPORT: 'REPORT'
}

export const TIME_PERIODS = {
  TODAY: 'TODAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
  QUARTER: 'QUARTER',
  YEAR: 'YEAR',
  YTD: 'YTD',
  CUSTOM: 'CUSTOM'
}

export const TIME_PERIOD_NAMES = {
  [TIME_PERIODS.TODAY]: 'Today',
  [TIME_PERIODS.WEEK]: 'This Week',
  [TIME_PERIODS.MONTH]: 'This Month',
  [TIME_PERIODS.QUARTER]: 'This Quarter',
  [TIME_PERIODS.YEAR]: 'This Year',
  [TIME_PERIODS.YTD]: 'Year to Date',
  [TIME_PERIODS.CUSTOM]: 'Custom Range'
}

export const REPORT_TYPES = {
  PORTFOLIO_SUMMARY: 'PORTFOLIO_SUMMARY',
  TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',
  PERFORMANCE: 'PERFORMANCE',
  HOLDINGS: 'HOLDINGS',
  FEES: 'FEES',
  TAX: 'TAX',
  COMPLIANCE: 'COMPLIANCE'
}

export const REPORT_TYPE_NAMES = {
  [REPORT_TYPES.PORTFOLIO_SUMMARY]: 'Portfolio Summary',
  [REPORT_TYPES.TRANSACTION_HISTORY]: 'Transaction History',
  [REPORT_TYPES.PERFORMANCE]: 'Performance Report',
  [REPORT_TYPES.HOLDINGS]: 'Holdings Report',
  [REPORT_TYPES.FEES]: 'Fee Report',
  [REPORT_TYPES.TAX]: 'Tax Report',
  [REPORT_TYPES.COMPLIANCE]: 'Compliance Report'
}

export const EXPORT_FORMATS = {
  PDF: 'PDF',
  CSV: 'CSV',
  EXCEL: 'EXCEL',
  JSON: 'JSON'
}

export const EXPORT_FORMAT_NAMES = {
  [EXPORT_FORMATS.PDF]: 'PDF',
  [EXPORT_FORMATS.CSV]: 'CSV',
  [EXPORT_FORMATS.EXCEL]: 'Excel',
  [EXPORT_FORMATS.JSON]: 'JSON'
}